spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: ~J4%I=l4
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update